-- Phase 1 request-review intake. This migration is intentionally fail-closed:
-- the global gate starts paused and every persona starts disabled. It accepts a
-- bounded, CAPTCHA-verified request only through the service-role RPC, writes
-- its audit trail in the same transaction, and queues a notification record.
-- It does not send email, draft review copy, create affiliate links, or publish.

begin;

create extension if not exists citext with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.product_review_global_controls (
  singleton smallint primary key default 1 check (singleton = 1),
  accepting_requests boolean not null default false,
  abuse_paused boolean not null default true,
  fingerprint_burst_limit integer not null default 3
    check (fingerprint_burst_limit between 1 and 20),
  fingerprint_daily_limit integer not null default 8
    check (fingerprint_daily_limit between 1 and 100),
  email_daily_limit integer not null default 5
    check (email_daily_limit between 1 and 50),
  persona_daily_limit integer not null default 50
    check (persona_daily_limit between 1 and 1000),
  global_burst_limit integer not null default 100
    check (global_burst_limit between 1 and 5000),
  global_daily_limit integer not null default 500
    check (global_daily_limit between 1 and 50000),
  updated_at timestamptz not null default now()
);

insert into public.product_review_global_controls (singleton)
values (1)
on conflict (singleton) do nothing;

create table if not exists public.product_review_settings (
  persona_id uuid primary key,
  owner uuid not null references public.profiles(id) on delete cascade,
  enabled boolean not null default false,
  destination_ledger_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (persona_id, owner)
    references public.personas(id, owner) on delete cascade,
  foreign key (destination_ledger_id, owner)
    references public.account_ledger(id, owner) on delete restrict,
  check (not enabled or destination_ledger_id is not null)
);

create table if not exists public.product_review_requests (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references public.profiles(id) on delete cascade,
  persona_id uuid not null,
  requester_email extensions.citext,
  requester_name text,
  product_name text not null,
  product_url text,
  reason text,
  consent_to_reply boolean not null default false,
  marketing_consent boolean not null default false,
  status text not null default 'request_received'
    check (status in (
      'request_received', 'triaged', 'declined', 'owner_testing',
      'evidence_ready', 'persona_draft', 'owner_approved', 'published',
      'corrected_or_withdrawn'
    )),
  captcha_verified_at timestamptz not null,
  request_fingerprint text not null
    check (request_fingerprint ~ '^[0-9a-f]{64}$'),
  dedupe_key text not null check (dedupe_key ~ '^[0-9a-f]{64}$'),
  idempotency_key uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  retention_expires_at timestamptz not null default (now() + interval '180 days'),
  foreign key (persona_id, owner)
    references public.personas(id, owner) on delete cascade,
  unique (persona_id, idempotency_key),
  unique (id, owner, persona_id),
  check (char_length(product_name) between 1 and 160),
  check (product_name !~ '[[:cntrl:]<>]'),
  check (requester_name is null or (
    char_length(requester_name) between 1 and 100
    and requester_name !~ '[[:cntrl:]<>]'
  )),
  check (requester_email is null or (
    char_length(requester_email::text) between 3 and 320
    and requester_email::text !~ '[[:cntrl:]<>]'
  )),
  check (product_url is null or (
    char_length(product_url) between 9 and 2048
    and product_url ~ '^https://'
    and product_url !~ '[[:cntrl:]<>]'
  )),
  check (reason is null or (
    char_length(reason) between 1 and 1500
    and reason !~ '[[:cntrl:]<>]'
  )),
  check (not consent_to_reply or requester_email is not null),
  check (not marketing_consent or requester_email is not null),
  check (retention_expires_at > created_at)
);

create table if not exists public.product_review_events (
  id bigint generated by default as identity primary key,
  request_id uuid,
  owner uuid not null references public.profiles(id) on delete cascade,
  persona_id uuid not null,
  event_type text not null check (event_type in (
    'request_received', 'duplicate_suppressed', 'rate_limited',
    'notification_queued', 'state_changed', 'pii_erased'
  )),
  actor_type text not null default 'service'
    check (actor_type in ('service', 'owner', 'system')),
  details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(details) = 'object' and octet_length(details::text) <= 4096),
  created_at timestamptz not null default now(),
  foreign key (persona_id, owner)
    references public.personas(id, owner) on delete cascade,
  foreign key (request_id, owner, persona_id)
    references public.product_review_requests(id, owner, persona_id)
    on delete set null (request_id)
);

create table if not exists public.product_review_notifications (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null,
  owner uuid not null references public.profiles(id) on delete cascade,
  persona_id uuid not null,
  destination_ledger_id uuid not null,
  status text not null default 'queued'
    check (status in (
      'queued', 'claimed', 'sent', 'failed', 'reconciliation_required',
      'cancelled'
    )),
  idempotency_key text not null unique,
  attempt_count integer not null default 0 check (attempt_count between 0 and 20),
  available_at timestamptz not null default now(),
  claimed_at timestamptz,
  provider_message_id_hash text,
  last_error_code text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (request_id),
  foreign key (request_id, owner, persona_id)
    references public.product_review_requests(id, owner, persona_id)
    on delete cascade,
  foreign key (destination_ledger_id, owner)
    references public.account_ledger(id, owner) on delete restrict,
  check (provider_message_id_hash is null or provider_message_id_hash ~ '^[0-9a-f]{64}$'),
  check (last_error_code !~ '[[:cntrl:]<>]' and char_length(last_error_code) <= 120)
);

create table if not exists public.product_review_rate_limits (
  scope text not null check (scope in (
    'fingerprint_15m', 'fingerprint_day', 'email_day', 'persona_day',
    'global_15m', 'global_day'
  )),
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  window_start timestamptz not null,
  hit_count integer not null default 1 check (hit_count > 0),
  expires_at timestamptz not null,
  primary key (scope, key_hash, window_start),
  check (expires_at > window_start)
);

create index if not exists product_review_requests_owner_created_idx
  on public.product_review_requests (owner, created_at desc);
create index if not exists product_review_requests_persona_dedupe_idx
  on public.product_review_requests (persona_id, dedupe_key, created_at desc);
create index if not exists product_review_events_owner_created_idx
  on public.product_review_events (owner, created_at desc);
create index if not exists product_review_notifications_queue_idx
  on public.product_review_notifications (available_at, created_at)
  where status = 'queued';
create index if not exists product_review_rate_limits_expiry_idx
  on public.product_review_rate_limits (expires_at);

alter table public.product_review_global_controls enable row level security;
alter table public.product_review_settings enable row level security;
alter table public.product_review_requests enable row level security;
alter table public.product_review_events enable row level security;
alter table public.product_review_notifications enable row level security;
alter table public.product_review_rate_limits enable row level security;

drop policy if exists "product review settings owner read" on public.product_review_settings;
create policy "product review settings owner read"
  on public.product_review_settings for select to authenticated
  using (auth.uid() = owner);

drop policy if exists "product review requests owner read" on public.product_review_requests;
create policy "product review requests owner read"
  on public.product_review_requests for select to authenticated
  using (auth.uid() = owner);

drop policy if exists "product review events owner read" on public.product_review_events;
create policy "product review events owner read"
  on public.product_review_events for select to authenticated
  using (auth.uid() = owner);

-- There are deliberately no browser policies for the global control, rate, or
-- notification tables. The notification table is a queue, not a send worker.
revoke all on public.product_review_global_controls from public, anon, authenticated;
revoke all on public.product_review_settings from public, anon, authenticated;
revoke all on public.product_review_requests from public, anon, authenticated;
revoke all on public.product_review_events from public, anon, authenticated;
revoke all on public.product_review_notifications from public, anon, authenticated;
revoke all on public.product_review_rate_limits from public, anon, authenticated;
grant select on public.product_review_settings to authenticated;
grant select on public.product_review_requests to authenticated;
grant select on public.product_review_events to authenticated;
grant all on public.product_review_global_controls to service_role;
grant all on public.product_review_settings to service_role;
grant all on public.product_review_requests to service_role;
grant all on public.product_review_events to service_role;
grant all on public.product_review_notifications to service_role;
grant all on public.product_review_rate_limits to service_role;
grant usage, select on sequence public.product_review_events_id_seq to service_role;

create or replace function public.touch_product_review_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function public.touch_product_review_updated_at()
  from public, anon, authenticated;

drop trigger if exists touch_product_review_settings
  on public.product_review_settings;
create trigger touch_product_review_settings
  before update on public.product_review_settings for each row
  execute function public.touch_product_review_updated_at();
drop trigger if exists touch_product_review_notifications
  on public.product_review_notifications;
create trigger touch_product_review_notifications
  before update on public.product_review_notifications for each row
  execute function public.touch_product_review_updated_at();

create or replace function public.configure_product_review(
  p_persona_id uuid,
  p_enabled boolean,
  p_destination_ledger_id uuid
)
returns public.product_review_settings
language plpgsql
security definer
set search_path = '' as $$
declare
  v_owner uuid := auth.uid();
  v_result public.product_review_settings%rowtype;
begin
  perform public.require_aal2();
  if p_persona_id is null or p_enabled is null then
    raise exception 'Persona and enabled state are required';
  end if;
  if not exists (
    select 1 from public.personas as persona
    where persona.id = p_persona_id and persona.owner = v_owner
  ) then
    raise exception 'Owned persona not found';
  end if;
  if p_enabled and p_destination_ledger_id is null then
    raise exception 'An owner-verified persona mailbox is required';
  end if;
  if p_destination_ledger_id is not null and not exists (
    select 1
    from public.account_ledger as ledger
    join public.gmail_credentials as credential
      on credential.ledger_id = ledger.id and credential.owner = ledger.owner
    where ledger.id = p_destination_ledger_id
      and ledger.owner = v_owner
      and ledger.persona_id = p_persona_id
      and ledger.provider = 'gmail'
      and ledger.suspended = false
      and trim(coalesce(ledger.login_email, '')) <> ''
  ) then
    raise exception 'Choose a connected, nonsuspended Gmail ledger for this persona';
  end if;

  insert into public.product_review_settings (
    persona_id, owner, enabled, destination_ledger_id
  ) values (
    p_persona_id, v_owner, p_enabled, p_destination_ledger_id
  )
  on conflict (persona_id) do update set
    enabled = excluded.enabled,
    destination_ledger_id = excluded.destination_ledger_id,
    updated_at = now()
  where public.product_review_settings.owner = v_owner
  returning * into v_result;

  if v_result.persona_id is null then
    raise exception 'Product-review settings ownership mismatch';
  end if;
  return v_result;
end;
$$;

revoke all on function public.configure_product_review(uuid, boolean, uuid)
  from public, anon, authenticated;
grant execute on function public.configure_product_review(uuid, boolean, uuid)
  to authenticated;

create or replace function public.set_product_review_global_control_service(
  p_accepting_requests boolean,
  p_abuse_paused boolean
)
returns boolean
language plpgsql
security definer
set search_path = '' as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise sqlstate '42501' using message = 'Service role required';
  end if;
  if p_accepting_requests is null or p_abuse_paused is null then
    raise exception 'Explicit global gate values are required';
  end if;
  update public.product_review_global_controls set
    accepting_requests = p_accepting_requests,
    abuse_paused = p_abuse_paused,
    updated_at = now()
  where singleton = 1;
  if not found then raise exception 'Global request-review control is missing'; end if;
  return true;
end;
$$;

revoke all on function public.set_product_review_global_control_service(boolean, boolean)
  from public, anon, authenticated;
grant execute on function public.set_product_review_global_control_service(boolean, boolean)
  to service_role;

create or replace function public.consume_product_review_rate_limit(
  p_scope text,
  p_key_hash text,
  p_window_start timestamptz,
  p_expires_at timestamptz,
  p_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = '' as $$
declare v_hits integer;
begin
  if p_scope not in (
    'fingerprint_15m', 'fingerprint_day', 'email_day', 'persona_day',
    'global_15m', 'global_day'
  ) or p_key_hash !~ '^[0-9a-f]{64}$' or p_limit < 1
    or p_expires_at <= p_window_start then
    raise exception 'Invalid request-review rate-limit input';
  end if;

  insert into public.product_review_rate_limits (
    scope, key_hash, window_start, hit_count, expires_at
  ) values (
    p_scope, p_key_hash, p_window_start, 1, p_expires_at
  )
  on conflict (scope, key_hash, window_start) do update set
    hit_count = public.product_review_rate_limits.hit_count + 1,
    expires_at = greatest(
      public.product_review_rate_limits.expires_at,
      excluded.expires_at
    )
  returning hit_count into v_hits;
  return v_hits <= p_limit;
end;
$$;

revoke all on function public.consume_product_review_rate_limit(
  text, text, timestamptz, timestamptz, integer
) from public, anon, authenticated, service_role;

create or replace function public.accept_product_review_request_service(
  p_persona_id uuid,
  p_idempotency_key uuid,
  p_requester_email text,
  p_requester_name text,
  p_product_name text,
  p_product_url text,
  p_reason text,
  p_consent_to_reply boolean,
  p_marketing_consent boolean,
  p_request_fingerprint text,
  p_requester_email_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = '' as $$
declare
  v_now timestamptz := clock_timestamp();
  v_day_start timestamptz;
  v_burst_start timestamptz;
  v_owner uuid;
  v_destination_ledger_id uuid;
  v_control public.product_review_global_controls%rowtype;
  v_existing_id uuid;
  v_request_id uuid;
  v_rate_scope text;
  v_dedupe_source text;
  v_dedupe_key text;
  v_persona_key text;
  v_global_key text;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise sqlstate '42501' using message = 'Service role required';
  end if;
  if p_persona_id is null or p_idempotency_key is null then
    raise exception 'Persona and idempotency key are required';
  end if;
  if char_length(trim(coalesce(p_product_name, ''))) not between 1 and 160
    or trim(coalesce(p_product_name, '')) ~ '[[:cntrl:]<>]' then
    raise exception 'Invalid product name';
  end if;
  if nullif(trim(coalesce(p_product_url, '')), '') is not null and (
    char_length(trim(p_product_url)) not between 9 and 2048
    or trim(p_product_url) !~ '^https://'
    or trim(p_product_url) ~ '[[:cntrl:]<>]'
  ) then
    raise exception 'Invalid product URL';
  end if;
  if nullif(trim(coalesce(p_requester_name, '')), '') is not null and (
    char_length(trim(p_requester_name)) > 100
    or trim(p_requester_name) ~ '[[:cntrl:]<>]'
  ) then
    raise exception 'Invalid requester name';
  end if;
  if nullif(trim(coalesce(p_reason, '')), '') is not null and (
    char_length(trim(p_reason)) > 1500
    or trim(p_reason) ~ '[[:cntrl:]<>]'
  ) then
    raise exception 'Invalid request reason';
  end if;
  if nullif(lower(trim(coalesce(p_requester_email, ''))), '') is not null and (
    char_length(trim(p_requester_email)) > 320
    or trim(p_requester_email) ~ '[[:cntrl:]<>[:space:]]'
    or trim(p_requester_email) !~ '^[^@]+@[^@]+[.][^@]+$'
  ) then
    raise exception 'Invalid requester email';
  end if;
  if (coalesce(p_consent_to_reply, false) or coalesce(p_marketing_consent, false))
    and nullif(trim(coalesce(p_requester_email, '')), '') is null then
    raise exception 'Consent requires a requester email';
  end if;
  if p_request_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid request fingerprint';
  end if;
  if nullif(trim(coalesce(p_requester_email, '')), '') is null then
    if coalesce(p_requester_email_hash, '') <> '' then
      raise exception 'Email hash cannot exist without requester email';
    end if;
  elsif p_requester_email_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid requester email hash';
  end if;

  select * into v_control
  from public.product_review_global_controls where singleton = 1;
  if not found or not v_control.accepting_requests or v_control.abuse_paused then
    return jsonb_build_object('disposition', 'suppressed');
  end if;

  select persona.owner, settings.destination_ledger_id
    into v_owner, v_destination_ledger_id
  from public.personas as persona
  join public.product_review_settings as settings
    on settings.persona_id = persona.id and settings.owner = persona.owner
  join public.agent_bindings as binding
    on binding.persona_id = persona.id and binding.owner = persona.owner
  join public.account_ledger as ledger
    on ledger.id = settings.destination_ledger_id
    and ledger.owner = persona.owner
    and ledger.persona_id = persona.id
  join public.gmail_credentials as credential
    on credential.ledger_id = ledger.id and credential.owner = ledger.owner
  where persona.id = p_persona_id
    and persona.visibility = 'public'
    and settings.enabled = true
    and binding.status = 'active'
    and binding.claim_state not in ('revoked', 'suspended')
    and ledger.provider = 'gmail'
    and ledger.suspended = false
    and trim(coalesce(ledger.login_email, '')) <> ''
  limit 1;
  if v_owner is null then
    return jsonb_build_object('disposition', 'suppressed');
  end if;

  select request.id into v_existing_id
  from public.product_review_requests as request
  where request.persona_id = p_persona_id
    and request.idempotency_key = p_idempotency_key;
  if v_existing_id is not null then
    return jsonb_build_object('disposition', 'duplicate', 'request_id', v_existing_id);
  end if;

  v_day_start := date_trunc('day', v_now at time zone 'UTC') at time zone 'UTC';
  v_burst_start := date_trunc('hour', v_now)
    + floor(extract(minute from v_now) / 15) * interval '15 minutes';
  v_persona_key := encode(extensions.digest(
    convert_to('persona:' || p_persona_id::text, 'UTF8'), 'sha256'
  ), 'hex');
  v_global_key := encode(extensions.digest(
    convert_to('request-review-global', 'UTF8'), 'sha256'
  ), 'hex');

  if not public.consume_product_review_rate_limit(
    'global_15m', v_global_key, v_burst_start,
    v_burst_start + interval '1 hour', v_control.global_burst_limit
  ) then v_rate_scope := 'global_15m'; end if;
  if v_rate_scope is null and not public.consume_product_review_rate_limit(
    'global_day', v_global_key, v_day_start,
    v_day_start + interval '2 days', v_control.global_daily_limit
  ) then v_rate_scope := 'global_day'; end if;
  if v_rate_scope is null and not public.consume_product_review_rate_limit(
    'fingerprint_15m', p_request_fingerprint, v_burst_start,
    v_burst_start + interval '1 hour', v_control.fingerprint_burst_limit
  ) then v_rate_scope := 'fingerprint_15m'; end if;
  if v_rate_scope is null and not public.consume_product_review_rate_limit(
    'fingerprint_day', p_request_fingerprint, v_day_start,
    v_day_start + interval '2 days', v_control.fingerprint_daily_limit
  ) then v_rate_scope := 'fingerprint_day'; end if;
  if v_rate_scope is null and p_requester_email_hash <> ''
    and not public.consume_product_review_rate_limit(
      'email_day', p_requester_email_hash, v_day_start,
      v_day_start + interval '2 days', v_control.email_daily_limit
    ) then v_rate_scope := 'email_day'; end if;
  if v_rate_scope is null and not public.consume_product_review_rate_limit(
    'persona_day', v_persona_key, v_day_start,
    v_day_start + interval '2 days', v_control.persona_daily_limit
  ) then v_rate_scope := 'persona_day'; end if;

  if v_rate_scope is not null then
    insert into public.product_review_events (
      request_id, owner, persona_id, event_type, details
    ) values (
      null, v_owner, p_persona_id, 'rate_limited',
      jsonb_build_object('scope', v_rate_scope)
    );
    return jsonb_build_object('disposition', 'suppressed');
  end if;

  v_dedupe_source := case
    when nullif(trim(coalesce(p_product_url, '')), '') is not null
      then 'url:' || lower(trim(p_product_url))
    else 'name:' || lower(regexp_replace(trim(p_product_name), '\s+', ' ', 'g'))
  end;
  v_dedupe_key := encode(extensions.digest(
    convert_to(v_dedupe_source, 'UTF8'), 'sha256'
  ), 'hex');

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_persona_id::text || ':' || v_dedupe_key, 0)
  );
  select request.id into v_existing_id
  from public.product_review_requests as request
  where request.persona_id = p_persona_id
    and request.dedupe_key = v_dedupe_key
    and request.created_at >= v_now - interval '30 days'
  order by request.created_at desc
  limit 1;
  if v_existing_id is not null then
    insert into public.product_review_events (
      request_id, owner, persona_id, event_type, details
    ) values (
      v_existing_id, v_owner, p_persona_id, 'duplicate_suppressed',
      jsonb_build_object('window_days', 30)
    );
    return jsonb_build_object('disposition', 'duplicate', 'request_id', v_existing_id);
  end if;

  insert into public.product_review_requests (
    owner, persona_id, requester_email, requester_name, product_name,
    product_url, reason, consent_to_reply, marketing_consent,
    captcha_verified_at, request_fingerprint, dedupe_key, idempotency_key
  ) values (
    v_owner, p_persona_id,
    nullif(lower(trim(coalesce(p_requester_email, ''))), ''),
    nullif(trim(coalesce(p_requester_name, '')), ''),
    trim(p_product_name),
    nullif(trim(coalesce(p_product_url, '')), ''),
    nullif(trim(coalesce(p_reason, '')), ''),
    coalesce(p_consent_to_reply, false),
    coalesce(p_marketing_consent, false),
    v_now, p_request_fingerprint, v_dedupe_key, p_idempotency_key
  )
  on conflict (persona_id, idempotency_key) do nothing
  returning id into v_request_id;
  if v_request_id is null then
    select request.id into v_request_id
    from public.product_review_requests as request
    where request.persona_id = p_persona_id
      and request.idempotency_key = p_idempotency_key;
    return jsonb_build_object('disposition', 'duplicate', 'request_id', v_request_id);
  end if;

  insert into public.product_review_events (
    request_id, owner, persona_id, event_type, details
  ) values (
    v_request_id, v_owner, p_persona_id, 'request_received',
    jsonb_build_object(
      'consent_to_reply', coalesce(p_consent_to_reply, false),
      'marketing_consent', coalesce(p_marketing_consent, false)
    )
  );
  insert into public.product_review_notifications (
    request_id, owner, persona_id, destination_ledger_id, idempotency_key
  ) values (
    v_request_id, v_owner, p_persona_id, v_destination_ledger_id,
    'request-review:' || v_request_id::text
  );
  insert into public.product_review_events (
    request_id, owner, persona_id, event_type, details
  ) values (
    v_request_id, v_owner, p_persona_id, 'notification_queued',
    jsonb_build_object('send_attempted', false)
  );

  return jsonb_build_object('disposition', 'accepted', 'request_id', v_request_id);
end;
$$;

revoke all on function public.accept_product_review_request_service(
  uuid, uuid, text, text, text, text, text, boolean, boolean, text, text
) from public, anon, authenticated;
grant execute on function public.accept_product_review_request_service(
  uuid, uuid, text, text, text, text, text, boolean, boolean, text, text
) to service_role;

create or replace function public.prune_product_review_rate_limits_service()
returns integer
language plpgsql
security definer
set search_path = '' as $$
declare v_deleted integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise sqlstate '42501' using message = 'Service role required';
  end if;
  delete from public.product_review_rate_limits where expires_at < now();
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function public.prune_product_review_rate_limits_service()
  from public, anon, authenticated;
grant execute on function public.prune_product_review_rate_limits_service()
  to service_role;

comment on table public.product_review_requests is
  'Private owner-readable request-review intake; request_fingerprint is a rotating HMAC and never a raw IP.';
comment on table public.product_review_notifications is
  'Service-only phase-1 notification queue. Migration 043 creates no sender or claim worker.';
comment on function public.accept_product_review_request_service(
  uuid, uuid, text, text, text, text, text, boolean, boolean, text, text
) is 'Service-only atomic request acceptance, limits, dedupe, audit, and queue insert. Returns an internal disposition; public callers receive a neutral receipt.';

commit;
